from __future__ import annotations

VALID_ANSATZES = {"hardware_efficient", "symmetry_preserving", "problem_inspired"}
VALID_OPTIMIZERS = {"COBYLA", "SPSA", "SLSQP", "BFGS"}
VALID_SHOT_ALLOCATIONS = {"equal", "coefficient_weighted", "variance_weighted"}
VALID_LOG_LEVELS = {"CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"}
VALID_ZNE_EXTRAPOLATORS = {"linear", "quadratic", "exponential"}
VALID_NOISE_BODIES = {
    "ideal",
    "local_dephasing",
    "amplitude_damping",
    "depolarizing",
    "correlated_zz_noise",
    "coherent_x_drift",
    "coherent_z_drift",
    "readout_only",
    "hardware",
}
NOISE_BODY_ALIASES = {
    "dephasing": "local_dephasing",
    "phase_damping": "local_dephasing",
    "amp_damp": "amplitude_damping",
    "correlated_zz": "correlated_zz_noise",
    "coherent_drift": "coherent_z_drift",
}

ONE_QUBIT_NOISE_GATES = ("id", "sx", "x", "rx", "ry", "rz", "h", "s", "sdg")
TWO_QUBIT_NOISE_GATES = ("cx", "cz", "ecr", "swap", "rzz", "rxx", "ryy", "crx", "cry", "crz")

DEFAULT_SPSA_LEARNING_RATE = 0.2
DEFAULT_SPSA_PERTURBATION = 0.15
DEFAULT_SPSA_ALPHA = 0.602
DEFAULT_SPSA_GAMMA = 0.101
DEFAULT_SPSA_STABILITY_RATIO = 0.1

DEFAULT_BEHAVIOR_WEAK_FIELD_RATIO = 0.75
DEFAULT_BEHAVIOR_NEAR_CRITICAL_RATIO = 1.25
DEFAULT_BEHAVIOR_LOW_NOISE_THRESHOLD = 0.005
DEFAULT_BEHAVIOR_MODERATE_NOISE_THRESHOLD = 0.01
DEFAULT_BEHAVIOR_SYMMETRY_RISK_WEIGHT = 2.0
DEFAULT_BEHAVIOR_OBSERVABLE_RISK_WEIGHT = 0.25
DEFAULT_BEHAVIOR_UNCERTAINTY_RISK_WEIGHT = 0.5

DEFAULT_GATE_ERROR = 0.01
DEFAULT_T1 = 50.0
DEFAULT_T2 = 70.0
DEFAULT_GATE_TIME = 0.1
DEFAULT_SEED = 42
DEFAULT_READOUT_ERROR = 0.0
DEFAULT_COUPLING = 1.0
DEFAULT_FIELD_STRENGTH = 1.0
DEFAULT_PERIODIC_BOUNDARY = False
DEFAULT_DEPTH = 2
DEFAULT_MAX_ITER = 100
DEFAULT_VERIFICATION_SHOTS = 4096
DEFAULT_PREFLIGHT_SHOTS = 256
DEFAULT_BASE_SHOTS = 512
DEFAULT_FINAL_SHOTS = 4096
DEFAULT_ENABLE_DYNAMIC_SHOTS = False
DEFAULT_ENABLE_ZNE = False
DEFAULT_ENABLE_READOUT_MITIGATION = True
DEFAULT_ZNE_FACTORS = (1, 3, 5)
DEFAULT_ZNE_EXTRAPOLATOR = "linear"
DEFAULT_PHYSICAL_VALIDITY_TOL = 0.05
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_OUTPUT_PREFIX = "fieldline_vqe"
DEFAULT_STUDY_OUTPUT_PREFIX = "fieldline_study"
DEFAULT_MAX_WORKERS = 1
DEFAULT_SYMMETRY_PENALTY_LAMBDA = 0.0
DEFAULT_CROSSOVER_SYMMETRY_PENALTY = 2.0
DEFAULT_CROSSOVER_OBSERVABLE_PENALTY = 0.25
DEFAULT_SHOT_ALLOCATION = "equal"
DEFAULT_NOISE_BODY = "ideal"
DEFAULT_NOISE_BODIES = ("ideal", "local_dephasing", "amplitude_damping", "correlated_zz_noise", "coherent_z_drift")
DEFAULT_NOISE_STRENGTHS = (0.0, 0.005, 0.01)
DEFAULT_NOISE_BODY_OUTPUT_PREFIX = "results/noise_bodies/noise_body_sweep"
DEFAULT_NOISE_BODY_CORRELATION = 0.5
DEFAULT_NOISE_BODY_COHERENCE_ANGLE = 0.0
DEFAULT_NOISE_BODY_READOUT_ERROR = 0.0

DEFAULT_SYSTEM_SIZES = (4, 6, 8)
DEFAULT_FIELD_STRENGTHS = (0.5, 1.0, 1.5)
DEFAULT_DEPTHS = (1, 2, 3)
DEFAULT_ANSATZES = ("hardware_efficient", "symmetry_preserving", "problem_inspired")
DEFAULT_OPTIMIZERS = ("COBYLA", "SPSA", "SLSQP")
DEFAULT_GATE_ERRORS = (0.0, 0.005, 0.01, 0.02)
DEFAULT_SEEDS = (7, 21)

DEFAULT_PHYSICS_SYMMETRY_WEIGHT = 2.0
DEFAULT_PHYSICS_OBSERVABLE_WEIGHT = 0.25
EXACT_DIAGONALIZATION_MAX_QUBITS = 10
DEFAULT_RUNTIME_OPTIMIZATION_LEVEL = 1
ZNE_EXPONENTIAL_INITIAL_RATE = 0.5
ZNE_CURVE_FIT_MAX_EVALS = 10000
NUMERIC_EPS = 1e-12
BUDGET_FALLBACK = 1e18

__all__ = [
    "VALID_ANSATZES", "VALID_OPTIMIZERS", "VALID_SHOT_ALLOCATIONS", "VALID_LOG_LEVELS", "VALID_ZNE_EXTRAPOLATORS", "VALID_NOISE_BODIES", "NOISE_BODY_ALIASES",
    "ONE_QUBIT_NOISE_GATES", "TWO_QUBIT_NOISE_GATES",
    "DEFAULT_SPSA_LEARNING_RATE", "DEFAULT_SPSA_PERTURBATION", "DEFAULT_SPSA_ALPHA", "DEFAULT_SPSA_GAMMA", "DEFAULT_SPSA_STABILITY_RATIO",
    "DEFAULT_BEHAVIOR_WEAK_FIELD_RATIO", "DEFAULT_BEHAVIOR_NEAR_CRITICAL_RATIO", "DEFAULT_BEHAVIOR_LOW_NOISE_THRESHOLD", "DEFAULT_BEHAVIOR_MODERATE_NOISE_THRESHOLD",
    "DEFAULT_BEHAVIOR_SYMMETRY_RISK_WEIGHT", "DEFAULT_BEHAVIOR_OBSERVABLE_RISK_WEIGHT", "DEFAULT_BEHAVIOR_UNCERTAINTY_RISK_WEIGHT",
    "DEFAULT_GATE_ERROR", "DEFAULT_T1", "DEFAULT_T2", "DEFAULT_GATE_TIME", "DEFAULT_SEED", "DEFAULT_READOUT_ERROR",
    "DEFAULT_COUPLING", "DEFAULT_FIELD_STRENGTH", "DEFAULT_PERIODIC_BOUNDARY", "DEFAULT_DEPTH", "DEFAULT_MAX_ITER",
    "DEFAULT_VERIFICATION_SHOTS", "DEFAULT_PREFLIGHT_SHOTS", "DEFAULT_BASE_SHOTS", "DEFAULT_FINAL_SHOTS",
    "DEFAULT_ENABLE_DYNAMIC_SHOTS", "DEFAULT_ENABLE_ZNE", "DEFAULT_ENABLE_READOUT_MITIGATION", "DEFAULT_ZNE_FACTORS",
    "DEFAULT_ZNE_EXTRAPOLATOR", "DEFAULT_PHYSICAL_VALIDITY_TOL", "DEFAULT_LOG_LEVEL", "DEFAULT_OUTPUT_PREFIX",
    "DEFAULT_STUDY_OUTPUT_PREFIX", "DEFAULT_MAX_WORKERS", "DEFAULT_SYMMETRY_PENALTY_LAMBDA",
    "DEFAULT_CROSSOVER_SYMMETRY_PENALTY", "DEFAULT_CROSSOVER_OBSERVABLE_PENALTY", "DEFAULT_SHOT_ALLOCATION",
    "DEFAULT_NOISE_BODY", "DEFAULT_NOISE_BODIES", "DEFAULT_NOISE_STRENGTHS", "DEFAULT_NOISE_BODY_OUTPUT_PREFIX",
    "DEFAULT_NOISE_BODY_CORRELATION", "DEFAULT_NOISE_BODY_COHERENCE_ANGLE", "DEFAULT_NOISE_BODY_READOUT_ERROR",
    "DEFAULT_SYSTEM_SIZES", "DEFAULT_FIELD_STRENGTHS", "DEFAULT_DEPTHS", "DEFAULT_ANSATZES", "DEFAULT_OPTIMIZERS", "DEFAULT_GATE_ERRORS", "DEFAULT_SEEDS",
    "DEFAULT_PHYSICS_SYMMETRY_WEIGHT", "DEFAULT_PHYSICS_OBSERVABLE_WEIGHT", "EXACT_DIAGONALIZATION_MAX_QUBITS",
    "DEFAULT_RUNTIME_OPTIMIZATION_LEVEL", "ZNE_EXPONENTIAL_INITIAL_RATE", "ZNE_CURVE_FIT_MAX_EVALS", "NUMERIC_EPS", "BUDGET_FALLBACK",
]
